### ISSUE TITLE
Grades for Assignment 2-3

### ISSUE THREAD

**Issue by matthewlevy** [terriha8/angular-exercise-2#1]
Assignment 2-3: Nothing was ever committed to GitHub, but I saw your C9 link...however...I need everything to be submitted via GH!....so I can only give you partial credit for each :-(

**Comment by terriha8** [comment]
I see some files that are committed to GitHub, Professor Levy. I don't understand? https://github.com/terriha8/angular-exercise-2

**Comment by matthewlevy** [comment]
There is no angularApp.js or index.ejs that you modified. :-(

**Comment by terriha8** [comment]
I misunderstood that we were supposed to commit before we made those changes. There's no way I can commit again and revise it? 
Sincerely,
Terri HaInformation Systems
San Franisco State Universityterriha8@gmail.com | (415) 795-0000-------- Original message --------From: "Dr. Matthew Levy" notifications@github.com Date: 9/27/2015  11:53 AM  (GMT-08:00) To: terriha8/angular-exercise-2 angular-exercise-2@noreply.github.com Cc: terriha8 terriha8@gmail.com Subject: Re: [angular-exercise-2] Grades for Assignment 2-3 (#1) 
There is no angularApp.js or index.ejs that you modified. :-(

**Comment by matthewlevy** [comment]
Hi Terri,

I can't do it as it would be unfair to others. However, I drop the lowest
exercise grade and there will be a lot more opportunities to make up for it.

--Matt

**Comment by terriha8** [comment]
Okay, thank you Professor Levy.

Sincerely,

Terri Ha
Information Systems
San Francisco State University
terriha8@gmail.com I (415) 795-0000
